import { Inter, Dancing_Script } from "next/font/google";
import "./globals.css";
import { ClerkProvider, UserButton } from "@clerk/nextjs";
import NestedHeader from "./components/NestedHeader";
import { Toaster } from "../@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Interview Mentor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <Toaster />
          <NestedHeader />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
